### ISSUE TITLE
wekaconfig doesn't handle non-US or non-EN locales

### ISSUE THREAD

**Issue by jackchallen** [weka/tools#109]
```
LANG=de_DE.UTF-8
LC_COLLATE=de_DE.UTF-8
LC_CTYPE=de_DE.UTF-8
LC_MESSAGES=de_DE.UTF-8

./wekaconfig
...Host group is Homogeneous.
Scanning Complete.  Press Enter to continue: 
starting UI...
Traceback (most recent call last):
  File "wekaconfig.py", line 69, in <module>
  File "wekatui/apNPSApplication.py", line 30, in run
  File "wekatui/npyssafewrapper.py", line 41, in wrapper
  File "wekatui/npyssafewrapper.py", line 82, in wrapper_no_fork
  File "locale.py", line 610, in setlocale
locale.Error: unsupported locale setting
[64776] Failed to execute script 'wekaconfig' due to unhandled exception!
```

**Comment by vince-weka** [comment]
The settings must be set in /etc/environment and the system rebooted or, alternatively you can use the localedef command like this:
`sudo localedef -i en_US -f UTF-8 en_US.UTF-8`

THEN run wekaconfig
