### ISSUE TITLE
weka_upgrade_cheker | AWS | backend OS check fails with exception

### ISSUE THREAD

**Issue by vrragosta** [weka/tools#198]
The following error was observed when running weka_upgrade_checker on an AWS cluster:

```
CHECKING IF OS IS SUPPORTED ON BACKENDS

Traceback (most recent call last):
  File "weka_upgrade_checker.py", line 1978, in <module>
    INFO(f"Cluster upgrade checks complete!")
  File "weka_upgrade_checker.py", line 1968, in main
    ssh_bk_hosts = weka_cluster_results[1]
  File "weka_upgrade_checker.py", line 1705, in backend_host_checks
    def backend_host_checks(backend_hosts, ssh_bk_hosts, weka_version, check_version, backend_ips, ssh_identity,
  File "weka_upgrade_checker.py", line 1366, in check_os_release
    if backend:
ValueError: not enough values to unpack (expected 2, got 1)
[12198] Failed to execute script 'weka_upgrade_checker' due to unhandled exception!
```

**Comment by vrragosta** [comment]
Closing -- user error...
